name: Eureka Server CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'discovery-server/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'discovery-server/**'
  workflow_dispatch:
jobs:
  build:
    name: Build Eureka Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 23 for Eureka Server
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: change directory to discovery server
        run: cd discovery-server
        
      - name: Printing files
        run: ls -a
        
      - name: Set executable permission for gradlew
        run: chmod +x gradlew
        
      # - name: Build Eureka Server with Gradle
      #   working-directory: ./discovery-server
      #   run: ./gradlew clean build
