name: Eureka Server CI

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-ci:
    uses: ./.github/workflows/movie-pipeline.yml
    with:
      service-directory: 'discovery-server'
